name: Run Set env

on: [workflow_dispatch]
     
jobs:  
  Windows-latest:
      runs-on: windows-latest
      
      steps:
        - name: 'Set env'          
          shell: pwsh
          run: |               
               $sgObjects = @()
                  $sgobject  = New-Object -TypeName Hashtable
                  $sgobject.SecurityGroup = @{ResourceIdScope= "Resource"; ResourceGroupName= "az-dna-112-rg-adlsresourceseq00760bjanq"; RBACRoleName = "Owner"}
                  $sgObjects += $sgobject
                  $sgobject  = New-Object -TypeName Hashtable
                  $sgobject.SecurityGroup =  @{ResourceIdScope= "Resource"; ResourceGroupName= "az-dna-112-rg-adlsresourceseq00761bjanq"; RBACRoleName = "Reader"}
                  $sgObjects += $sgobject
                  $sgobject  = New-Object -TypeName Hashtable
                  $sgobject.SecurityGroup =  @{ResourceIdScope= "Resource"; ResourceGroupName= "az-dna-112-rg-adlsresourceseq00762bjanq"; RBACRoleName = "Owner"}
                  $sgObjects += $sgobject
                  $sgobject  = New-Object -TypeName Hashtable
                  $sgobject.SecurityGroup = @{ResourceIdScope= "Resource"; ResourceGroupName= "az-dna-112-rg-adlsresourceseq00763bjanq"; RBACRoleName = "Reader"}
                  $sgObjects += $sgobject
                  "adlsRbacs=$($sgObjects)" >> $env:GITHUB_ENV
             
        - name: 'Get env'                    
          shell: pwsh
          run: |                         
               $sgObjects = {{env.adlsRbacs}}
               $sgObjects.GetType()               
               Write-Output $sgObjects
               
               foreach ($item in $sgObjects){
                   Write-Output $item
                   $item | ConvertTo-Json -Depth 5
                 }
