name: Run Set env

on: [workflow_dispatch]
     
jobs:  
  Windows-latest:
      runs-on: windows-latest
      
      steps:
        - name: 'Set env'          
          with:
             inlineScript: |               
               $sgObjects = @()
                  $sgobject  = New-Object -TypeName Hashtable
                  $sgobject.SecurityGroup = @{ResourceIdScope= "Resource"; ResourceGroupName= "az-dna-112-rg-adlsresourceseq00760bjanq"; RBACRoleName = "Owner"}
                  $sgObjects += $sgobject
                  $sgobject  = New-Object -TypeName Hashtable
                  $sgobject.SecurityGroup =  @{ResourceIdScope= "Resource"; ResourceGroupName= "az-dna-112-rg-adlsresourceseq00761bjanq"; RBACRoleName = "Reader"}
                  $sgObjects += $sgobject
                  $sgobject  = New-Object -TypeName Hashtable
                  $sgobject.SecurityGroup =  @{ResourceIdScope= "Resource"; ResourceGroupName= "az-dna-112-rg-adlsresourceseq00762bjanq"; RBACRoleName = "Owner"}
                  $sgObjects += $sgobject
                  $sgobject  = New-Object -TypeName Hashtable
                  $sgobject.SecurityGroup = @{ResourceIdScope= "Resource"; ResourceGroupName= "az-dna-112-rg-adlsresourceseq00763bjanq"; RBACRoleName = "Reader"}
                  $sgObjects += $sgobject
                  "adlsRbacs=$($sgObjects)" >> $env:GITHUB_ENV

             azPSVersion: "latest"
             
        - name: 'Get env'
          with:
             inlineScript: |               
               $sgObjects = {{env.adlsRbacs}}
               Write-Output $sgObjects
             azPSVersion: "latest"    
