name: Run Set env

on: 
  workflow_dispatch:
    inputs:
      businessEnvironment:
        description: 'ADLS Environment'
        type: choice
        default: 'Non-Prod'
        options:
         - Prod
         - Non-Prod
        required: true

     
jobs:  
  Windows-latest:
      runs-on: windows-latest
      
      steps:
       
           - name: Set environments values
             run: |
                   if ('${{ github.event.inputs.businessEnvironment }}' -eq 'Non-Prod' ){
                       Write-Output 'Non prod'
                       $envs = @('dev','tst','pre')
                       echo "parameters.envs.value=$envs" >> $env:GITHUB_ENV
                   }
                   else{
                       Write-Output 'prod'
                       $envs = @('prd')
                       echo "envsParam=$envs" >> $env:GITHUB_ENV
                   }
       
          
          
           - name: 'Get env'                    
             shell: pwsh
             run: |                         
                    $sgObjects = ${env:envsParam}
                    Write-Output "(Invoke-Expression ${env:envsParam})"             

