name: Run Get-ADGroups - OIDC

on: [workflow_dispatch]

permissions:
      id-token: write
      contents: read
      
jobs:  
  Windows-latest:
      runs-on: windows-latest
      environment: dev
      steps:
        - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
            enable-AzPSSession: true

        - name: 'Set env'
          uses: azure/powershell@v1
          with:
             inlineScript: |               
               $sgObjects = @()
                  $sgobject  = New-Object -TypeName Hashtable
                  $sgobject.SecurityGroup = @{ResourceIdScope= "Resource"; ResourceGroupName= "az-dna-112-rg-adlsresourceseq00760bjanq"; RBACRoleName = "Owner"}
                  $sgObjects += $sgobject
                  $sgobject  = New-Object -TypeName Hashtable
                  $sgobject.SecurityGroup =  @{ResourceIdScope= "Resource"; ResourceGroupName= "az-dna-112-rg-adlsresourceseq00761bjanq"; RBACRoleName = "Reader"}
                  $sgObjects += $sgobject
                  $sgobject  = New-Object -TypeName Hashtable
                  $sgobject.SecurityGroup =  @{ResourceIdScope= "Resource"; ResourceGroupName= "az-dna-112-rg-adlsresourceseq00762bjanq"; RBACRoleName = "Owner"}
                  $sgObjects += $sgobject
                  $sgobject  = New-Object -TypeName Hashtable
                  $sgobject.SecurityGroup = @{ResourceIdScope= "Resource"; ResourceGroupName= "az-dna-112-rg-adlsresourceseq00763bjanq"; RBACRoleName = "Reader"}
                  $sgObjects += $sgobject
                  "parameters.AdlsRbacs.value=$($sgObjects)" >> $env:GITHUB_ENV

             azPSVersion: "latest"
             
        - name: 'Get env'
          uses: azure/powershell@v1
          with:
             inlineScript: |               
               $sgObjects = {env:parameters.AdlsRbacs.value}
               $sgObjects
             azPSVersion: "latest"    
